import React, { forwardRef } from 'react';
import { JokeData } from '../types';
import { BookOpen, Laugh, MessageCircle, Mic } from 'lucide-react';

interface JokeCardProps {
  joke: JokeData;
}

const JokeCard = forwardRef<HTMLDivElement, JokeCardProps>(({ joke }, ref) => {
  return (
    <div 
      ref={ref}
      className="bg-white p-8 rounded-xl border-2 border-[#1D201F] shadow-[8px_8px_0px_0px_rgba(29,32,31,0.15)] max-w-2xl w-full mx-auto text-[#1D201F] relative overflow-hidden"
    >
      {/* Decorative colored bar at top */}
      <div className="absolute top-0 left-0 w-full h-4 bg-gradient-to-r from-[#00CFFF] via-[#FFA9A3] to-[#FFBC42]"></div>

      {/* Header */}
      <div className="flex justify-between items-start mt-2 mb-6">
        <span className="bg-[#1D201F] text-white text-xs font-bold px-2 py-1 rounded uppercase tracking-wider">
          {joke.category || 'General'}
        </span>
        <span className="text-xs text-gray-500 font-mono">
           Aussie Joke Mate
        </span>
      </div>

      {/* Main Joke Content */}
      <div className="mb-8">
        <div className="flex items-start gap-4 mb-4">
            <div className="bg-[#00CFFF] p-2 rounded-full border border-black shrink-0">
                <MessageCircle size={24} />
            </div>
            <div>
                <p className="text-xl font-medium leading-relaxed">{joke.content}</p>
            </div>
        </div>
        
        <div className="flex items-start gap-4 pl-4 border-l-4 border-[#FFBC42]">
             <div className="bg-[#FFBC42] p-2 rounded-full border border-black shrink-0">
                <Laugh size={24} />
            </div>
            <div>
                <p className="text-2xl font-black italic">{joke.punchline}</p>
            </div>
        </div>
      </div>

      <hr className="border-t-2 border-dashed border-gray-200 my-6" />

      {/* Educational Content */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        
        {/* Why it's funny */}
        <div className="col-span-1 md:col-span-2 bg-[#F7F7F5] p-4 rounded-lg border border-gray-200">
            <h3 className="font-bold mb-2 flex items-center gap-2">
                <Mic size={16} /> Why it's funny
            </h3>
            <p className="text-sm text-gray-700 leading-relaxed">
                {joke.whyItsFunny}
            </p>
        </div>

        {/* Slang */}
        {joke.slang && joke.slang.length > 0 && (
          <div className="bg-[#E0F7FA] p-4 rounded-lg border border-[#00CFFF]/30">
            <h3 className="font-bold text-[#00838F] mb-2 flex items-center gap-2 text-sm uppercase tracking-wide">
              🇦🇺 Aussie Slang
            </h3>
            <ul className="space-y-2">
              {joke.slang.map((item, idx) => (
                <li key={idx} className="text-sm">
                  <span className="font-bold">{item.term}</span>: {item.definition}
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Vocabulary */}
        {joke.vocabulary && joke.vocabulary.length > 0 && (
          <div className="bg-[#FFF3E0] p-4 rounded-lg border border-[#FFBC42]/30">
             <h3 className="font-bold text-[#EF6C00] mb-2 flex items-center gap-2 text-sm uppercase tracking-wide">
              <BookOpen size={16} /> Vocabulary
            </h3>
            <ul className="space-y-2">
              {joke.vocabulary.map((item, idx) => (
                <li key={idx} className="text-sm">
                  <span className="font-bold">{item.word}</span>: {item.definition}
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>
      
      {/* Footer watermark for image */}
      <div className="mt-8 text-center opacity-40 text-[10px] uppercase tracking-[0.2em] font-bold">
        Generated by Aussie Joke Mate
      </div>
    </div>
  );
});

JokeCard.displayName = 'JokeCard';

export default JokeCard;